PATCH /api/2.0/tenders/ad87aa89b4ac42d7a942cefce42e6504/awards/7d40fcea66f0471a8cfc7064b13e22ca/complaints/e2bfb91ae56248d79c8179d57d30a89e HTTP/1.0
Authorization: Basic cmV2aWV3ZXI6
Content-Length: 33
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "satisfied"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "satisfied", 
    "dateDecision": "2016-03-17T09:44:21.958298+02:00", 
    "documents": [
      {
        "author": "complaint_owner", 
        "title": "Complaint_Attachement.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/ad87aa89b4ac42d7a942cefce42e6504/awards/7d40fcea66f0471a8cfc7064b13e22ca/complaints/e2bfb91ae56248d79c8179d57d30a89e/documents/508276b0962243cdbba5abaed61612d5?download=6bdf8eb4ff9a409f921e08d29d51cf07", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-17T09:44:20.049358+02:00", 
        "id": "508276b0962243cdbba5abaed61612d5", 
        "dateModified": "2016-03-17T09:44:20.049401+02:00"
      }, 
      {
        "author": "aboveThresholdReviewers", 
        "title": "ComplaintResolution.pdf", 
        "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/ad87aa89b4ac42d7a942cefce42e6504/awards/7d40fcea66f0471a8cfc7064b13e22ca/complaints/e2bfb91ae56248d79c8179d57d30a89e/documents/f44786ecabce4e56a12b37882b82f1ba?download=d7c9708327e9415dbab2324999828a76", 
        "format": "application/pdf", 
        "documentOf": "tender", 
        "datePublished": "2016-03-17T09:44:21.729693+02:00", 
        "id": "f44786ecabce4e56a12b37882b82f1ba", 
        "dateModified": "2016-03-17T09:44:21.729733+02:00"
      }
    ], 
    "description": "Умови виставлені замовником не містять достатньо інформації, щоб заявка мала сенс.", 
    "title": "Недостатньо інформації", 
    "author": {
      "contactPoint": {
        "email": "soleksuk@gmail.com", 
        "telephone": "+380 (432) 21-69-30", 
        "name": "Сергій Олексюк"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
        "id": "13313462", 
        "uri": "http://sch10.edu.vn.ua/"
      }, 
      "name": "ДКП «Школяр»", 
      "address": {
        "postalCode": "21100", 
        "countryName": "Україна", 
        "streetAddress": "вул. Островського, 33", 
        "region": "м. Вінниця", 
        "locality": "м. Вінниця"
      }
    }, 
    "dateAccepted": "2016-03-17T09:44:21.235656+02:00", 
    "dateSubmitted": "2016-03-17T09:44:20.287728+02:00", 
    "complaintID": "UA-2016-03-17-000001.1", 
    "date": "2016-03-17T09:44:19.827366+02:00", 
    "acceptance": true, 
    "type": "complaint", 
    "id": "e2bfb91ae56248d79c8179d57d30a89e"
  }
}

