PATCH /api/2.0/tenders/516c3fb3a7cd4094bd38ec7c81c59a25/contracts/560d90d290b54d1a8f7b015bccc1f9ec?acc_token=e9444f5c71f340eea46d968d0fe83272 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 118
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "period": {
      "startDate": "2016-03-17T09:44:10.711720+02:00", 
      "endDate": "2017-03-17T09:44:10.711767+02:00"
    }
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "pending", 
    "items": [
      {
        "description": "Послуги шкільних їдалень", 
        "classification": {
          "scheme": "CPV", 
          "description": "Послуги з харчування у школах", 
          "id": "55523100-3"
        }, 
        "additionalClassifications": [
          {
            "scheme": "ДКПП", 
            "id": "55.51.10.300", 
            "description": "Послуги шкільних їдалень"
          }
        ], 
        "id": "2dc54675d6364e2baffbc0f8e74432ac", 
        "unit": {
          "code": "MON", 
          "name": "month"
        }, 
        "quantity": 9
      }
    ], 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "period": {
      "startDate": "2016-03-17T09:44:10.711720+02:00", 
      "endDate": "2017-03-17T09:44:10.711767+02:00"
    }, 
    "value": {
      "currency": "UAH", 
      "amount": 238.0, 
      "valueAddedTaxIncluded": true
    }, 
    "awardID": "372b1fb5209141be957af8f005d0f650", 
    "id": "560d90d290b54d1a8f7b015bccc1f9ec", 
    "contractID": "UA-2016-03-17-000001-1"
  }
}

