PATCH /api/2.0/tenders/2fc899fc534a4403ad9f4cfeb3cd2978/awards/1104a7818f694cbf8ddbcaa6298a5797?acc_token=43f372e70a8b4470914dcaefd86af95e HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 30
Content-Type: application/json
Host: api-sandbox.openprocurement.org

{
  "data": {
    "status": "active"
  }
}

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "status": "active", 
    "complaintPeriod": {
      "startDate": "2016-03-17T09:44:26.009692+02:00", 
      "endDate": "2016-03-22T09:44:26.210797+02:00"
    }, 
    "suppliers": [
      {
        "contactPoint": {
          "email": "soleksuk@gmail.com", 
          "telephone": "+380 (432) 21-69-30", 
          "name": "Сергій Олексюк"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "legalName": "Державне комунальне підприємство громадського харчування «Школяр»", 
          "id": "13313462", 
          "uri": "http://sch10.edu.vn.ua/"
        }, 
        "name": "ДКП «Школяр»", 
        "address": {
          "postalCode": "21100", 
          "countryName": "Україна", 
          "streetAddress": "вул. Островського, 33", 
          "region": "м. Вінниця", 
          "locality": "м. Вінниця"
        }
      }
    ], 
    "value": {
      "currency": "UAH", 
      "amount": 475000.0, 
      "valueAddedTaxIncluded": true
    }, 
    "date": "2016-03-17T09:44:26.008294+02:00", 
    "id": "1104a7818f694cbf8ddbcaa6298a5797"
  }
}

