GET /api/2.0/tenders?opt_pretty=1 HTTP/1.0
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "next_page": {
    "path": "/api/2.0/tenders?offset=2016-03-17T09%3A44%3A08.962146%2B02%3A00", 
    "uri": "http://api-sandbox.openprocurement.org/api/2.0/tenders?offset=2016-03-17T09%3A44%3A08.962146%2B02%3A00", 
    "offset": "2016-03-17T09:44:08.962146+02:00"
  }, 
  "data": [
    {
      "id": "516c3fb3a7cd4094bd38ec7c81c59a25", 
      "dateModified": "2016-03-17T09:44:08.962146+02:00"
    }
  ]
}

