PUT /api/2.0/tenders/516c3fb3a7cd4094bd38ec7c81c59a25/documents/f00d59da55a141f6ba4884a649cbcc80?acc_token=e9444f5c71f340eea46d968d0fe83272 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 189
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy461785190417$
Host: api-sandbox.openprocurement.org

Response: 200 OK
Content-Type: application/json; charset=UTF-8
{
  "data": {
    "title": "Notice-2.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/516c3fb3a7cd4094bd38ec7c81c59a25/documents/f00d59da55a141f6ba4884a649cbcc80?download=2ed10e94fef14cf8822ce8f42dd888ed", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-03-17T09:44:09.312341+02:00", 
    "id": "f00d59da55a141f6ba4884a649cbcc80", 
    "dateModified": "2016-03-17T09:44:09.493360+02:00"
  }
}

