POST /api/2.0/tenders/516c3fb3a7cd4094bd38ec7c81c59a25/documents?acc_token=e9444f5c71f340eea46d968d0fe83272 HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 186
Content-Type: multipart/form-data; boundary=----------a_BoUnDaRy708873601598$
Host: api-sandbox.openprocurement.org

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.0/tenders/516c3fb3a7cd4094bd38ec7c81c59a25/documents/f00d59da55a141f6ba4884a649cbcc80
{
  "data": {
    "title": "Notice.pdf", 
    "url": "http://api-sandbox.openprocurement.org/api/2.0/tenders/516c3fb3a7cd4094bd38ec7c81c59a25/documents/f00d59da55a141f6ba4884a649cbcc80?download=bb0c5112109a40639373e4a6c4e1c88a", 
    "format": "application/pdf", 
    "documentOf": "tender", 
    "datePublished": "2016-03-17T09:44:09.312341+02:00", 
    "id": "f00d59da55a141f6ba4884a649cbcc80", 
    "dateModified": "2016-03-17T09:44:09.312381+02:00"
  }
}

